# Generated by Django 2.1 on 2018-09-04 03:48

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_id', models.CharField(max_length=200)),
                ('folder_name', models.CharField(default=None, max_length=200)),
                ('folder_email', models.EmailField(default=None, max_length=254)),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GDFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('user'), 'jzhou@ripple.com'),)), upload_to='Safe')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GDFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_id', models.CharField(max_length=200, unique=True)),
                ('folder_name', models.CharField(default=None, max_length=200)),
                ('folder_email', models.EmailField(default=None, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
